/*
 * 
 * Copyright 2009 digma543
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * JGREFunctionOptions.java
 * 
 */

/*
 * JGREFunctionOptions.java
 *
 * Created on 2009/6/28, 下午 02:25:41
 */
package jgre.view;

/**
 *
 * @author digma543
 */
public class JGREFunctionOptions extends javax.swing.JPanel {

  /** Creates new form JGREFunctionOptions */
  public JGREFunctionOptions() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    memoWordButton = new javax.swing.JButton();
    reviewWordButton = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jgre.view.JGREApp.class).getContext().getResourceMap(JGREFunctionOptions.class);
    memoWordButton.setFont(resourceMap.getFont("BigButton.font")); // NOI18N
    memoWordButton.setIcon(resourceMap.getIcon("memoWordButton.icon")); // NOI18N
    memoWordButton.setText(resourceMap.getString("memoWordButton.text")); // NOI18N
    memoWordButton.setActionCommand(resourceMap.getString("memoWordButton.actionCommand")); // NOI18N
    memoWordButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
    memoWordButton.setName("memoWordButton"); // NOI18N
    memoWordButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        memoWordButtonActionPerformed(evt);
      }
    });
    add(memoWordButton);

    reviewWordButton.setFont(resourceMap.getFont("BigButton.font")); // NOI18N
    reviewWordButton.setIcon(resourceMap.getIcon("reviewWordButton.icon")); // NOI18N
    reviewWordButton.setText(resourceMap.getString("reviewWordButton.text")); // NOI18N
    reviewWordButton.setActionCommand(resourceMap.getString("reviewWordButton.actionCommand")); // NOI18N
    reviewWordButton.setName("reviewWordButton"); // NOI18N
    add(reviewWordButton);

    jButton3.setFont(resourceMap.getFont("BigButton.font")); // NOI18N
    jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
    jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
    jButton3.setName("jButton3"); // NOI18N
    add(jButton3);

    jButton4.setFont(resourceMap.getFont("BigButton.font")); // NOI18N
    jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
    jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
    jButton4.setActionCommand(ViewEnum.EXAM.toString());
    jButton4.setName("jButton4"); // NOI18N
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    add(jButton4);

    jButton5.setFont(resourceMap.getFont("BigButton.font")); // NOI18N
    jButton5.setIcon(resourceMap.getIcon("jButton5.icon")); // NOI18N
    jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
    jButton5.setName("jButton5"); // NOI18N
    add(jButton5);

    getAccessibleContext().setAccessibleParent(this);
  }// </editor-fold>//GEN-END:initComponents

    private void memoWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoWordButtonActionPerformed
      System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_memoWordButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      controller.changeView(ViewEnum.EXAM.toString());
    }//GEN-LAST:event_jButton4ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton memoWordButton;
  private javax.swing.JButton reviewWordButton;
  // End of variables declaration//GEN-END:variables
  @InjectController()
  ViewController controller;
}
